# INTERFAZ DE USUARIO INICIAL PARA UN INVENTARIO DE BEBIDAS
# TITULO, NOMBRE DEL ALGORITMO, NOMBRE DEL PROGRAMA.
print("\n") #SALTA UNA LINEA (COMO DAR ENTER)
print("----- INVENTARIO DE BEBIDAS -----") 
print("\nProductos disponibles:")  
print("\nCoca-Cola / Fanta / Sprite / Agua")

# SOLICITAR AL USUARIO QUE INGRESE EL NOMBRE, PRECIO Y CANTIDAD DEL PRODUCTO.
# CREAMOS UNA VARIABLE PARA CADA DATO QUE VAMOS A SOLICITAR AL USUARIO, Y UTILIZAMOS LA FUNCION input() PARA OBTENER LOS DATOS INGRESADOS POR EL USUARIO.
# TAMBIEN AGREGAMOS UN CICLO "while" PARA VALIDAR QUE EL USUARIO INGRESE UN NOMBRE DEL PRODUCTO, UN PRECIO Y UNA CANTIDAD VALIDOS (QUE SEAN NUMEROS POSITIVOS).

nombre_producto = input("\nIngrese el nombre de la bebida: ")

while True: # UTILIZAMOS UN CICLO "while" PARA VALIDAR QUE EL USUARIO INGRESE UN NUMERO POSIVO PARA EL PRECIO DE LA BEBIDA.
    try:
        precio_producto = float(input("\nIngrese el precio de la bebida: ")) # UTILIZAMOS float() PARA CONVERTIR EL DATO INGRESADO POR EL USUARIO A UN NUMERO DECIMAL, YA QUE EL PRECIO PUEDE TENER DECIMALES.
        if precio_producto <= 0: # VALIDAMOS QUE EL PRECIO SEA UN NUMERO POSITIVO, SI EL USUARIO INGRESA UN NUMERO NEGATIVO O CERO, MOSTRAMOS UN MENSAJE DE ERROR Y VOLVEMOS A SOLICITAR EL PRECIO HASTA QUE INGRESE UN DATO VALIDO.
            print("Por favor, ingrese un precio válido (número positivo).") # VOLVEMOS A SOLICITAR AL USUARIO QUE INGRESE EL PRECIO HASTA QUE INGRESE UN DATO VALIDO.
        else: 
            break # SI EL DATO ES VALIDO, SALIMOS DEL CICLO
    except ValueError:
        print("Por favor, ingrese un precio válido (número).")

while True:
    try:
        cantidad_producto = int(input("\nIngrese la cantidad de la bebida: ")) # UTILIZAMOS int() PARA CONVERTIR EL DATO INGRESADO POR EL USUARIO A UN NUMERO ENTERO, YA QUE LA CANTIDAD DEBE SER UN NUMERO ENTERO.
        if cantidad_producto <= 0: # VALIDAMOS QUE LA CANTIDAD SEA UN NUMERO POSITIVO, SI EL USUARIO INGRESA UN NUMERO NEGATIVO O CERO, MOSTRAMOS UN MENSAJE DE ERROR Y VOLVEMOS A SOLICITAR LA CANTIDAD HASTA QUE INGRESE UN DATO VALIDO.
            print("Por favor, ingrese una cantidad válida (número positivo).")
        else:
            break # SI EL DATO ES VALIDO, SALIMOS DEL CICLO
    except ValueError: # SI EL USUARIO INGRESA UN DATO QUE NO ES UN NUMERO, SE GENERA UNA EXCEPCION ValueError, Y MOSTRAMOS UN MENSAJE DE ERROR.
        print("Por favor, ingrese una cantidad válida (número entero).") # VOLVEMOS A SOLICITAR AL USUARIO QUE INGRESE LA CANTIDAD HASTA QUE INGRESE UN DATO VALIDO.

# FORMULA PARA CALCULAR EL COSTO TOTAL = PRECIO DE LA BEBIDA * CANTIDAD DE LA BEBIDA, Y MOSTRAMOS LOS RESULTADOS AL USUARIO UTILIZANDO LA FUNCION print() PARA MOSTRAR EL NOMBRE DEL PRODUCTO, EL PRECIO, LA CANTIDAD Y EL COSTO TOTAL.
costo_total = precio_producto * cantidad_producto
print(f"\nProducto: {nombre_producto} / Precio: {precio_producto} / Cantidad: {cantidad_producto} / Total: {costo_total}")
print("\n") # SALTA UNA LINEA AL FINAL DEL PROGRAMA
# COMENTARIO GENERAL: ESTE CODIGO ES UNA INTERFAZ DE USUARIO INICIAL 
# PARA UN INVENTARIO DE BEBIDAS, DONDE SE SOLICITA AL USUARIO QUE INGRESE EL NOMBRE, 
# PRECIO Y CANTIDAD DEL PRODUCTO, Y SE CALCULA EL COSTO TOTAL DEL PRODUCTO.